Section7
PNQT/Practichtmlcss pull request #18
Opened 2024-10-30 17:10 UTC by PNQT

2024-11-04 11:32 UTC, PhamNhuQuocBao requested changes

2024-11-04 11:32 UTC, PhamNhuQuocBao commented on src/layout/main.html
> +            <img src="assets/icons/layer_1.svg" alt="">
do not leave the alt value empty. let fix all.

2024-11-04 11:32 UTC, PhamNhuQuocBao commented on src/layout/main.html
> +                    <img src="assets/icons/ellipse 22.svg" alt="">
avoid naming files with spaces, I have already mentioned this issue.

2024-11-04 11:32 UTC, PhamNhuQuocBao commented on src/stylesheet/pages/home/_testimonials.scss
format code.

2024-11-09 16:09 UTC, datmaiz commented
resolve conflicts, please

2024-11-09 19:17 UTC, merged